export const UPDATE_CURRENT_INTERVENTION = 'UPDATE_CURRENT_INTERVENTION';
export const SHOW_TOAST = 'SHOW_TOAST';
export const CLOSE_TOAST = 'CLOSE_TOAST';
export const UPDATE_ROUTE_DETAILS = 'UPDATE_ROUTE_DETAILS';
