export const RESET_UNSAVED_UPLOADS = 'RESET_UNSAVED_UPLOADS';
export const RESET_UPLOADS_IN_PROGRESS = 'RESET_UPLOADS_IN_PROGRESS';
export const INCREASE_UPLOADS_IN_PROGRESS = 'INCREASE_UPLOADS_IN_PROGRESS';
export const DECREASE_UPLOADS_IN_PROGRESS = 'DECREASE_UPLOADS_IN_PROGRESS';
export const INCREASE_UNSAVED_UPLOADS = 'INCREASE_UNSAVED_UPLOADS';
export const DECREASE_UNSAVED_UPLOADS = 'DECREASE_UNSAVED_UPLOADS';
