FROM node:8-alpine
RUN apk update

RUN apk add --update bash

RUN apk add git
RUN npm i -g npm@5.6.0
RUN npm install -g --unsafe-perm polymer-cli
RUN npm install -g gulp
RUN npm install -g typescript

WORKDIR /code
