version: 2
jobs:
  test:
    working_directory: ~/code
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: node:11.9.0
    steps:
      - checkout
      - run:
          name: "Pull Submodule"
          command: |
            git submodule init
            git submodule update --checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: rm -rf node_modules/@unicef-polymer/etools-* & npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Polymer3 Build
          command: npm run build
          no_output_timeout: 25m
      - run:
          name: Run Tests
          command: |
            echo "skipping tests for now: xvfb-run polymer test --skip-selenium-install"

  build_and_deploy:
    working_directory: ~/code
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: node:11.9.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Exporting revision number
          command: |
            REVNO=${CIRCLE_SHA1}
            BUILDDATE=$(date -u +%F_%T)
            sed -i "0,/revNo/s//$REVNO/" package.json
            sed -i "0,/bDate/s//$BUILDDATE/" package.json
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
           # build and push Docker image
      - run:
          name: Building the image
          command: |
            TAG=${CIRCLE_BRANCH}
            docker build -t unicef/etools-pmp:$TAG .
      - run:
          name: Pushing to Docker Hub
          command: |
            TAG=${CIRCLE_BRANCH}
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push unicef/etools-pmp:$TAG

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
                - staging
                - develop
                - epd
      - build_and_deploy:
          filters:
            branches:
              only:
                - master
                - staging
                - develop
                - epd
